function out = RealGARCH_logPriors(theta,prior)
% LOGPRIORS calculate log of priors for RealGARCH

w       = theta(:,1);
beta    = theta(:,2);
gamma   = theta(:,3);
nu      = theta(:,4);
xi      = theta(:,5);
psi     = theta(:,6);
tau1    = theta(:,7);
tau2    = theta(:,8);
sigma2u = theta(:,9);

out  =  log(gampdf(w,prior.w_a0,1/prior.w_b0))...
            +log(betapdf(beta,prior.beta_a0,prior.beta_b0))...
            +log(betapdf(gamma,prior.gamma_a0,prior.gamma_b0))...
            +log(gampdf(nu,prior.nu_a0,1/prior.nu_b0))...
            +log(gampdf(xi,prior.xi_a0,1/prior.xi_b0))...
            +log(gampdf(psi,prior.psi_a0,1/prior.psi_b0))...
            +log(normpdf(tau1,prior.tau1_mu,sqrt(prior.tau1_var)))...
            +log(normpdf(tau2,prior.tau2_mu,sqrt(prior.tau2_var)))...
            +log(gampdf(sigma2u,prior.sigma2u_a0,1/prior.sigma2u_b0));
        
end

